
export interface Exercise {
  name: string;
  muscle: string;
  subMuscle: string;
  secondaryMuscles: string;
}

export const EXERCISES_DATA: Exercise[] = [
  // CHEST - Upper Chest
  { name: 'Incline Barbell Bench Press', muscle: 'CHEST', subMuscle: 'Upper Chest', secondaryMuscles: 'Triceps, Front Delts' },
  { name: 'Incline Dumbbell Bench Press', muscle: 'CHEST', subMuscle: 'Upper Chest', secondaryMuscles: 'Triceps, Front Delts, Serratus Anterior' },
  { name: 'Incline Smith Machine Press', muscle: 'CHEST', subMuscle: 'Upper Chest', secondaryMuscles: 'Triceps, Front Delts' },
  { name: 'Incline Cable Press', muscle: 'CHEST', subMuscle: 'Upper Chest', secondaryMuscles: 'Triceps, Front Delts' },
  { name: 'Incline Dumbbell Fly', muscle: 'CHEST', subMuscle: 'Upper Chest', secondaryMuscles: 'Front Delts, Biceps (Short Head)' },
  { name: 'Incline Cable Fly', muscle: 'CHEST', subMuscle: 'Upper Chest', secondaryMuscles: 'Front Delts, Serratus Anterior' },
  { name: 'Incline Hammer Strength Press', muscle: 'CHEST', subMuscle: 'Upper Chest', secondaryMuscles: 'Triceps, Front Delts' },
  { name: 'Incline Landmine Press', muscle: 'CHEST', subMuscle: 'Upper Chest', secondaryMuscles: 'Front Delts, Triceps, Core' },
  { name: 'High-to-Low Cable Press', muscle: 'CHEST', subMuscle: 'Upper Chest', secondaryMuscles: 'Lower Chest, Front Delts' },
  { name: 'Incline Guillotine Press', muscle: 'CHEST', subMuscle: 'Upper Chest', secondaryMuscles: 'Front Delts, Triceps' },
  { name: 'Incline Machine Chest Press', muscle: 'CHEST', subMuscle: 'Upper Chest', secondaryMuscles: 'Triceps, Front Delts' },
  { name: 'Incline Around-the-World Fly', muscle: 'CHEST', subMuscle: 'Upper Chest', secondaryMuscles: 'Middle Chest, Front Delts' },
  { name: 'Low-Cable to High-Cable Fly', muscle: 'CHEST', subMuscle: 'Upper Chest', secondaryMuscles: 'Front Delts, Upper Abs' },
  { name: 'Incline Squeeze Press', muscle: 'CHEST', subMuscle: 'Upper Chest', secondaryMuscles: 'Triceps, Inner Chest' },
  { name: 'Reverse-Grip Incline Bench Press', muscle: 'CHEST', subMuscle: 'Upper Chest', secondaryMuscles: 'Triceps, Upper Lats' },
  
  // CHEST - Middle Chest
  { name: 'Flat Barbell Bench Press', muscle: 'CHEST', subMuscle: 'Middle Chest', secondaryMuscles: 'Triceps, Front Delts' },
  { name: 'Flat Dumbbell Bench Press', muscle: 'CHEST', subMuscle: 'Middle Chest', secondaryMuscles: 'Triceps, Front Delts, Serratus Anterior' },
  { name: 'Flat Smith Press', muscle: 'CHEST', subMuscle: 'Middle Chest', secondaryMuscles: 'Triceps, Front Delts' },
  { name: 'Flat Hammer Strength Chest Press', muscle: 'CHEST', subMuscle: 'Middle Chest', secondaryMuscles: 'Triceps, Front Delts' },
  { name: 'Flat Dumbbell Fly', muscle: 'CHEST', subMuscle: 'Middle Chest', secondaryMuscles: 'Front Delts' },
  { name: 'Cable Fly (Chest Height)', muscle: 'CHEST', subMuscle: 'Middle Chest', secondaryMuscles: 'Front Delts, Serratus Anterior' },
  { name: 'Close-Grip Bench Press (Chest Focus)', muscle: 'CHEST', subMuscle: 'Middle Chest', secondaryMuscles: 'Triceps, Front Delts' },
  { name: 'Push-Ups', muscle: 'CHEST', subMuscle: 'Middle Chest', secondaryMuscles: 'Triceps, Front Delts, Core' },
  { name: 'Weighted Push-Ups', muscle: 'CHEST', subMuscle: 'Middle Chest', secondaryMuscles: 'Triceps, Front Delts, Core' },
  { name: 'Svend Press', muscle: 'CHEST', subMuscle: 'Middle Chest', secondaryMuscles: 'Front Delts, Forearms (Isometric)' },
  { name: 'Machine Chest Fly', muscle: 'CHEST', subMuscle: 'Middle Chest', secondaryMuscles: 'Front Delts' },
  { name: 'Cable Crossover (Mid-Level)', muscle: 'CHEST', subMuscle: 'Middle Chest', secondaryMuscles: 'Inner Chest, Front Delts' },
  { name: 'Plate Pinch Press', muscle: 'CHEST', subMuscle: 'Middle Chest', secondaryMuscles: 'Front Delts, Triceps' },
  { name: 'Iso-Lateral Chest Press Machine', muscle: 'CHEST', subMuscle: 'Middle Chest', secondaryMuscles: 'Triceps, Front Delts' },
  { name: 'Stability Ball Dumbbell Chest Press', muscle: 'CHEST', subMuscle: 'Middle Chest', secondaryMuscles: 'Core, Triceps, Shoulders' },

  // CHEST - Lower Chest
  { name: 'Decline Barbell Bench Press', muscle: 'CHEST', subMuscle: 'Lower Chest', secondaryMuscles: 'Triceps, Front Delts' },
  { name: 'Decline Dumbbell Bench Press', muscle: 'CHEST', subMuscle: 'Lower Chest', secondaryMuscles: 'Triceps, Front Delts' },
  { name: 'Decline Smith Press', muscle: 'CHEST', subMuscle: 'Lower Chest', secondaryMuscles: 'Triceps, Front Delts' },
  { name: 'Decline Hammer Strength Press', muscle: 'CHEST', subMuscle: 'Lower Chest', secondaryMuscles: 'Triceps, Front Delts' },
  { name: 'High-to-Low Cable Fly', muscle: 'CHEST', subMuscle: 'Lower Chest', secondaryMuscles: 'Serratus Anterior, Middle Chest' },
  { name: 'Decline Dumbbell Fly', muscle: 'CHEST', subMuscle: 'Lower Chest', secondaryMuscles: 'Front Delts' },
  { name: 'Cable Dip Pressdown', muscle: 'CHEST', subMuscle: 'Lower Chest', secondaryMuscles: 'Triceps, Front Delts' },
  { name: 'Chest Dips', muscle: 'CHEST', subMuscle: 'Lower Chest', secondaryMuscles: 'Triceps, Front Delts' },
  { name: 'Weighted Chest Dips', muscle: 'CHEST', subMuscle: 'Lower Chest', secondaryMuscles: 'Triceps, Front Delts' },
  { name: 'Decline Machine Chest Press', muscle: 'CHEST', subMuscle: 'Lower Chest', secondaryMuscles: 'Triceps, Front Delts' },
  { name: 'Lower-Pulley Chest Fly', muscle: 'CHEST', subMuscle: 'Lower Chest', secondaryMuscles: 'Upper Chest, Front Delts' },
  { name: 'Underhand Cable Press (Decline Arc)', muscle: 'CHEST', subMuscle: 'Lower Chest', secondaryMuscles: 'Triceps, Front Delts' },
  { name: 'Kneeling Low Cable Press', muscle: 'CHEST', subMuscle: 'Lower Chest', secondaryMuscles: 'Core, Upper Chest' },
  { name: 'Medicine Ball Push-ups (Feet Elevated)', muscle: 'CHEST', subMuscle: 'Lower Chest', secondaryMuscles: 'Upper Chest, Triceps, Core' },
  { name: 'Decline Around-the-World Fly', muscle: 'CHEST', subMuscle: 'Lower Chest', secondaryMuscles: 'Middle Chest, Front Delts' },

  // BACK - Lats
  { name: 'Pull-Ups', muscle: 'BACK', subMuscle: 'Lats (Latissimus Dorsi)', secondaryMuscles: 'Biceps, Rhomboids, Rear Delts' },
  { name: 'Chin-Ups', muscle: 'BACK', subMuscle: 'Lats (Latissimus Dorsi)', secondaryMuscles: 'Biceps, Rear Delts, Brachialis' },
  { name: 'Lat Pulldown', muscle: 'BACK', subMuscle: 'Lats (Latissimus Dorsi)', secondaryMuscles: 'Biceps, Rhomboids, Traps' },
  { name: 'Wide-Grip Pulldown', muscle: 'BACK', subMuscle: 'Lats (Latissimus Dorsi)', secondaryMuscles: 'Teres Major, Biceps' },
  { name: 'Close-Grip Pulldown', muscle: 'BACK', subMuscle: 'Lats (Latissimus Dorsi)', secondaryMuscles: 'Biceps, Lower Traps' },
  { name: 'Reverse-Grip Pulldown', muscle: 'BACK', subMuscle: 'Lats (Latissimus Dorsi)', secondaryMuscles: 'Biceps, Rhomboids' },
  { name: 'Single-Arm Lat Pulldown', muscle: 'BACK', subMuscle: 'Lats (Latissimus Dorsi)', secondaryMuscles: 'Core, Biceps' },
  { name: 'Straight-Arm Pulldown', muscle: 'BACK', subMuscle: 'Lats (Latissimus Dorsi)', secondaryMuscles: 'Triceps (Long Head), Rear Delts, Core' },
  { name: 'Cable Pullover', muscle: 'BACK', subMuscle: 'Lats (Latissimus Dorsi)', secondaryMuscles: 'Triceps (Long Head), Serratus Anterior' },
  { name: 'Dumbbell Pullover', muscle: 'BACK', subMuscle: 'Lats (Latissimus Dorsi)', secondaryMuscles: 'Chest, Triceps (Long Head)' },
  { name: 'Machine Pullover', muscle: 'BACK', subMuscle: 'Lats (Latissimus Dorsi)', secondaryMuscles: 'Rear Delts, Triceps (Long Head)' },
  { name: 'Neutral-Grip Pulldown', muscle: 'BACK', subMuscle: 'Lats (Latissimus Dorsi)', secondaryMuscles: 'Biceps, Brachialis' },
  { name: 'Weighted Pull-Ups', muscle: 'BACK', subMuscle: 'Lats (Latissimus Dorsi)', secondaryMuscles: 'Biceps, Rhomboids, Forearms' },
  { name: 'Assisted Pull-Ups', muscle: 'BACK', subMuscle: 'Lats (Latissimus Dorsi)', secondaryMuscles: 'Biceps, Rhomboids' },
  { name: 'Kneeling Single-Arm Pulldown', muscle: 'BACK', subMuscle: 'Lats (Latissimus Dorsi)', secondaryMuscles: 'Core, Obliques' },
  { name: 'Iso-Lateral Lat Pulldown Machine', muscle: 'BACK', subMuscle: 'Lats (Latissimus Dorsi)', secondaryMuscles: 'Biceps, Middle Back' },
  { name: 'Decline Pullover', muscle: 'BACK', subMuscle: 'Lats (Latissimus Dorsi)', secondaryMuscles: 'Lower Lats, Triceps' },
  { name: '“J” Pulldown', muscle: 'BACK', subMuscle: 'Lats (Latissimus Dorsi)', secondaryMuscles: 'Rear Delts, Lower Lats' },
  { name: 'Kayak Pulldown', muscle: 'BACK', subMuscle: 'Lats (Latissimus Dorsi)', secondaryMuscles: 'Obliques, Core, Rear Delts' },
  { name: 'Behind-the-Neck Pulldown', muscle: 'BACK', subMuscle: 'Lats (Latissimus Dorsi)', secondaryMuscles: 'Upper Traps, Rhomboids' },

  // BACK - Rhomboids
  { name: 'Bent Over Barbell Row', muscle: 'BACK', subMuscle: 'Rhomboids (Middle Back)', secondaryMuscles: 'Lats, Biceps, Spinal Erectors' },
  { name: 'T-Bar Row', muscle: 'BACK', subMuscle: 'Rhomboids (Middle Back)', secondaryMuscles: 'Lats, Biceps, Traps' },
  { name: 'One-Arm Dumbbell Row', muscle: 'BACK', subMuscle: 'Rhomboids (Middle Back)', secondaryMuscles: 'Lats, Biceps, Core' },
  { name: 'Seated Cable Row', muscle: 'BACK', subMuscle: 'Rhomboids (Middle Back)', secondaryMuscles: 'Biceps, Lats, Traps' },
  { name: 'Machine Row', muscle: 'BACK', subMuscle: 'Rhomboids (Middle Back)', secondaryMuscles: 'Biceps, Lats' },
  { name: 'Chest-Supported Row', muscle: 'BACK', subMuscle: 'Rhomboids (Middle Back)', secondaryMuscles: 'Biceps, Rear Delts' },
  { name: 'Meadows Row', muscle: 'BACK', subMuscle: 'Rhomboids (Middle Back)', secondaryMuscles: 'Lats, Biceps, Grip' },
  { name: 'Wide-Grip Seated Row', muscle: 'BACK', subMuscle: 'Rhomboids (Middle Back)', secondaryMuscles: 'Rear Delts, Traps' },
  { name: 'V-Grip Seated Row', muscle: 'BACK', subMuscle: 'Rhomboids (Middle Back)', secondaryMuscles: 'Lats, Biceps' },
  { name: 'Kroc Row', muscle: 'BACK', subMuscle: 'Rhomboids (Middle Back)', secondaryMuscles: 'Lats, Biceps, Forearms, Upper Traps' },
  { name: 'Pendlay Row', muscle: 'BACK', subMuscle: 'Rhomboids (Middle Back)', secondaryMuscles: 'Lats, Biceps, Hamstrings, Core' },
  { name: 'Seal Row', muscle: 'BACK', subMuscle: 'Rhomboids (Middle Back)', secondaryMuscles: 'Biceps, Rear Delts' },
  { name: 'Landmine Row', muscle: 'BACK', subMuscle: 'Rhomboids (Middle Back)', secondaryMuscles: 'Lats, Biceps, Core' },
  { name: 'Standing Cable Row', muscle: 'BACK', subMuscle: 'Rhomboids (Middle Back)', secondaryMuscles: 'Core, Biceps, Lats' },
  { name: 'Hammer Strength Row', muscle: 'BACK', subMuscle: 'Rhomboids (Middle Back)', secondaryMuscles: 'Biceps, Lats' },

  // BACK - Erector Spinae
  { name: 'Deadlift', muscle: 'BACK', subMuscle: 'Erector Spinae (Lower Back)', secondaryMuscles: 'Hamstrings, Glutes, Forearms, Traps, Lats' },
  { name: 'Romanian Deadlift', muscle: 'BACK', subMuscle: 'Erector Spinae (Lower Back)', secondaryMuscles: 'Hamstrings, Glutes, Forearms' },
  { name: 'Stiff-Leg Deadlift', muscle: 'BACK', subMuscle: 'Erector Spinae (Lower Back)', secondaryMuscles: 'Hamstrings, Glutes' },
  { name: 'Hyperextensions', muscle: 'BACK', subMuscle: 'Erector Spinae (Lower Back)', secondaryMuscles: 'Glutes, Hamstrings' },
  { name: 'Reverse Hyperextensions', muscle: 'BACK', subMuscle: 'Erector Spinae (Lower Back)', secondaryMuscles: 'Glutes, Hamstrings' },
  { name: 'Good Mornings', muscle: 'BACK', subMuscle: 'Erector Spinae (Lower Back)', secondaryMuscles: 'Hamstrings, Glutes' },
  { name: 'Back Extension Machine', muscle: 'BACK', subMuscle: 'Erector Spinae (Lower Back)', secondaryMuscles: 'Glutes' },
  { name: 'Trap Bar Deadlift', muscle: 'BACK', subMuscle: 'Erector Spinae (Lower Back)', secondaryMuscles: 'Quads, Glutes, Hamstrings, Traps' },
  { name: 'Jefferson Curl', muscle: 'BACK', subMuscle: 'Erector Spinae (Lower Back)', secondaryMuscles: 'Hamstrings, Core' },
  { name: 'Cable Lower-Back Extensions', muscle: 'BACK', subMuscle: 'Erector Spinae (Lower Back)', secondaryMuscles: 'Glutes' },

  // BACK - Traps
  { name: 'Barbell Shrugs', muscle: 'BACK', subMuscle: 'Traps', secondaryMuscles: 'Forearms, Neck' },
  { name: 'Dumbbell Shrugs', muscle: 'BACK', subMuscle: 'Traps', secondaryMuscles: 'Forearms' },
  { name: 'Behind-the-Back Shrugs', muscle: 'BACK', subMuscle: 'Traps', secondaryMuscles: 'Forearms, Rear Delts' },
  { name: 'Cable Shrugs', muscle: 'BACK', subMuscle: 'Traps', secondaryMuscles: 'Forearms' },
  { name: 'Machine Shrugs', muscle: 'BACK', subMuscle: 'Traps', secondaryMuscles: 'None (Pure Isolation)' },
  { name: 'Farmer\'s Walk', muscle: 'BACK', subMuscle: 'Traps', secondaryMuscles: 'Forearms, Core, Glutes, Calves' },
  { name: 'Upright Row', muscle: 'BACK', subMuscle: 'Traps', secondaryMuscles: 'Side Delts, Biceps' },
  { name: 'Incline Dumbbell Shrug', muscle: 'BACK', subMuscle: 'Traps', secondaryMuscles: 'Rear Delts, Rhomboids' },
  { name: 'Plate Shrugs', muscle: 'BACK', subMuscle: 'Traps', secondaryMuscles: 'Forearms' },
  { name: 'Barbell High Pull', muscle: 'BACK', subMuscle: 'Traps', secondaryMuscles: 'Side Delts, Glutes, Hamstrings (Explosive)' },
  { name: 'Smith Machine Shrugs', muscle: 'BACK', subMuscle: 'Traps', secondaryMuscles: 'Forearms' },
  { name: 'Kelso Shrug', muscle: 'BACK', subMuscle: 'Traps', secondaryMuscles: 'Rhomboids, Rear Delts' },
  { name: 'Power Shrugs', muscle: 'BACK', subMuscle: 'Traps', secondaryMuscles: 'Calves, Glutes, Forearms' },

  // BACK - Teres Major-Minor
  { name: 'Straight-Arm Pulldown (Teres Emphasis)', muscle: 'BACK', subMuscle: 'Teres Major-Minor', secondaryMuscles: 'Lats, Rear Delts' },
  { name: 'Kneeling Lat Row', muscle: 'BACK', subMuscle: 'Teres Major-Minor', secondaryMuscles: 'Core, Biceps' },
  { name: 'Low Cable Row (Elbows Out)', muscle: 'BACK', subMuscle: 'Teres Major-Minor', secondaryMuscles: 'Rear Delts, Rhomboids' },
  { name: 'Dumbbell Row to Hip', muscle: 'BACK', subMuscle: 'Teres Major-Minor', secondaryMuscles: 'Lower Lats, Biceps' },
  { name: 'Lat-Focused Underhand Row', muscle: 'BACK', subMuscle: 'Teres Major-Minor', secondaryMuscles: 'Biceps, Lats' },
  { name: 'Cross-Body Cable Row', muscle: 'BACK', subMuscle: 'Teres Major-Minor', secondaryMuscles: 'Rear Delts, Rhomboids' },
  { name: 'Rear Delt Row (Hits Teres)', muscle: 'BACK', subMuscle: 'Teres Major-Minor', secondaryMuscles: 'Rear Delts, Rhomboids, Traps' },
  { name: 'High Cable Partial Row', muscle: 'BACK', subMuscle: 'Teres Major-Minor', secondaryMuscles: 'Upper Lats, Rear Delts' },
  { name: 'Chest-Supported Neutral Row', muscle: 'BACK', subMuscle: 'Teres Major-Minor', secondaryMuscles: 'Biceps, Brachialis' },
  { name: 'Plate-Loaded High Row', muscle: 'BACK', subMuscle: 'Teres Major-Minor', secondaryMuscles: 'Lats, Biceps' },
  { name: 'Cable Iso Teres Pull', muscle: 'BACK', subMuscle: 'Teres Major-Minor', secondaryMuscles: 'Rear Delts' },

  // SHOULDERS - Front Deltoid
  { name: 'Barbell Shoulder Press', muscle: 'SHOULDERS', subMuscle: 'Front Deltoid', secondaryMuscles: 'Triceps, Side Delts, Upper Chest' },
  { name: 'Dumbbell Shoulder Press', muscle: 'SHOULDERS', subMuscle: 'Front Deltoid', secondaryMuscles: 'Triceps, Side Delts' },
  { name: 'Arnold Press', muscle: 'SHOULDERS', subMuscle: 'Front Deltoid', secondaryMuscles: 'Side Delts, Triceps, Rotator Cuff' },
  { name: 'Smith Machine Shoulder Press', muscle: 'SHOULDERS', subMuscle: 'Front Deltoid', secondaryMuscles: 'Triceps' },
  { name: 'Front Raise Dumbbells', muscle: 'SHOULDERS', subMuscle: 'Front Deltoid', secondaryMuscles: 'Upper Chest, Serratus Anterior' },
  { name: 'Front Raise Plate', muscle: 'SHOULDERS', subMuscle: 'Front Deltoid', secondaryMuscles: 'Upper Chest, Forearms' },
  { name: 'Barbell Front Raise', muscle: 'SHOULDERS', subMuscle: 'Front Deltoid', secondaryMuscles: 'Upper Chest, Core' },
  { name: 'Landmine Shoulder Press', muscle: 'SHOULDERS', subMuscle: 'Front Deltoid', secondaryMuscles: 'Triceps, Upper Chest, Core' },
  { name: 'Cable Front Raise', muscle: 'SHOULDERS', subMuscle: 'Front Deltoid', secondaryMuscles: 'Upper Chest' },
  { name: 'Machine Shoulder Press', muscle: 'SHOULDERS', subMuscle: 'Front Deltoid', secondaryMuscles: 'Triceps' },
  { name: 'Z-Press', muscle: 'SHOULDERS', subMuscle: 'Front Deltoid', secondaryMuscles: 'Core, Hip Flexors, Triceps' },
  { name: 'Kneeling Barbell Press', muscle: 'SHOULDERS', subMuscle: 'Front Deltoid', secondaryMuscles: 'Core, Triceps' },
  { name: 'Military Press', muscle: 'SHOULDERS', subMuscle: 'Front Deltoid', secondaryMuscles: 'Triceps, Core, Glutes' },
  { name: 'Resistance Band Front Raise', muscle: 'SHOULDERS', subMuscle: 'Front Deltoid', secondaryMuscles: 'Upper Chest' },
  { name: 'Single-Arm Dumbbell Press', muscle: 'SHOULDERS', subMuscle: 'Front Deltoid', secondaryMuscles: 'Core, Obliques, Triceps' },

  // SHOULDERS - Side Deltoid
  { name: 'Dumbbell Lateral Raise', muscle: 'SHOULDERS', subMuscle: 'Side Deltoid', secondaryMuscles: 'Front Delts, Traps' },
  { name: 'Cable Lateral Raise', muscle: 'SHOULDERS', subMuscle: 'Side Deltoid', secondaryMuscles: 'Front Delts, Traps' },
  { name: 'Machine Lateral Raise', muscle: 'SHOULDERS', subMuscle: 'Side Deltoid', secondaryMuscles: 'None' },
  { name: 'Seated Lateral Raise', muscle: 'SHOULDERS', subMuscle: 'Side Deltoid', secondaryMuscles: 'Front Delts' },
  { name: 'Lean-Away Lateral Raise', muscle: 'SHOULDERS', subMuscle: 'Side Deltoid', secondaryMuscles: 'Core, Front Delts' },
  { name: 'Dead-Stop Lateral Raise', muscle: 'SHOULDERS', subMuscle: 'Side Deltoid', secondaryMuscles: 'Front Delts' },
  { name: 'Upright Row (Side Delt Variation)', muscle: 'SHOULDERS', subMuscle: 'Side Deltoid', secondaryMuscles: 'Traps, Biceps' },
  { name: 'Dumbbell “W’s”', muscle: 'SHOULDERS', subMuscle: 'Side Deltoid', secondaryMuscles: 'Rear Delts, Rotator Cuff' },
  { name: 'Lateral Raise Partial Reps', muscle: 'SHOULDERS', subMuscle: 'Side Deltoid', secondaryMuscles: 'Front Delts' },
  { name: 'Behind-Back Cable Raise', muscle: 'SHOULDERS', subMuscle: 'Side Deltoid', secondaryMuscles: 'Front Delts' },
  { name: 'Landmine Lateral Lift', muscle: 'SHOULDERS', subMuscle: 'Side Deltoid', secondaryMuscles: 'Core, Traps' },
  { name: 'Delt Destroyer Set Raise', muscle: 'SHOULDERS', subMuscle: 'Side Deltoid', secondaryMuscles: 'Front Delts, Rear Delts' },
  { name: 'Plate Lateral Raise', muscle: 'SHOULDERS', subMuscle: 'Side Deltoid', secondaryMuscles: 'Forearms, Front Delts' },
  { name: 'Single-Arm Machine Lateral Raise', muscle: 'SHOULDERS', subMuscle: 'Side Deltoid', secondaryMuscles: 'Core' },
  { name: 'Cross-Body Cable Lateral Raise', muscle: 'SHOULDERS', subMuscle: 'Side Deltoid', secondaryMuscles: 'Rear Delts, Traps' },

  // SHOULDERS - Posterior Deltoid
  { name: 'Reverse Pec Deck', muscle: 'SHOULDERS', subMuscle: 'Posterior Deltoid (Rear)', secondaryMuscles: 'Rhomboids, Mid-Traps' },
  { name: 'Bent-Over Rear Delt Raise', muscle: 'SHOULDERS', subMuscle: 'Posterior Deltoid (Rear)', secondaryMuscles: 'Rhomboids, Traps' },
  { name: 'Face Pull', muscle: 'SHOULDERS', subMuscle: 'Posterior Deltoid (Rear)', secondaryMuscles: 'Traps, Rotator Cuff, Brachialis' },
  { name: 'Rear Delt Cable Fly', muscle: 'SHOULDERS', subMuscle: 'Posterior Deltoid (Rear)', secondaryMuscles: 'Rhomboids, Mid-Traps' },
  { name: 'Chest-Supported Reverse Fly', muscle: 'SHOULDERS', subMuscle: 'Posterior Deltoid (Rear)', secondaryMuscles: 'Rhomboids' },
  { name: 'Prone Rear Delt Raise', muscle: 'SHOULDERS', subMuscle: 'Posterior Deltoid (Rear)', secondaryMuscles: 'Rhomboids, Traps' },
  { name: 'Wide-Grip Row to Chest', muscle: 'SHOULDERS', subMuscle: 'Posterior Deltoid (Rear)', secondaryMuscles: 'Rhomboids, Traps, Biceps' },
  { name: 'Rear Delt Barbell Row', muscle: 'SHOULDERS', subMuscle: 'Posterior Deltoid (Rear)', secondaryMuscles: 'Rhomboids, Lats, Biceps' },
  { name: 'High Cable Rear Delt Pull-Apart', muscle: 'SHOULDERS', subMuscle: 'Posterior Deltoid (Rear)', secondaryMuscles: 'Traps, Rhomboids' },
  { name: 'Single-Arm Reverse Cable Fly', muscle: 'SHOULDERS', subMuscle: 'Posterior Deltoid (Rear)', secondaryMuscles: 'Core, Rhomboids' },
  { name: 'Incline Bench Rear Raise', muscle: 'SHOULDERS', subMuscle: 'Posterior Deltoid (Rear)', secondaryMuscles: 'Rhomboids' },
  { name: 'TRX Rear Delt Fly', muscle: 'SHOULDERS', subMuscle: 'Posterior Deltoid (Rear)', secondaryMuscles: 'Core, Rhomboids' },
  { name: 'Resistance Band Face Pull', muscle: 'SHOULDERS', subMuscle: 'Posterior Deltoid (Rear)', secondaryMuscles: 'Rotator Cuff, Traps' },
  { name: 'Reverse Dumbbell Swing', muscle: 'SHOULDERS', subMuscle: 'Posterior Deltoid (Rear)', secondaryMuscles: 'Traps' },
  { name: 'Cable High Pull', muscle: 'SHOULDERS', subMuscle: 'Posterior Deltoid (Rear)', secondaryMuscles: 'Side Delts, Traps' },

  // ABS & CORE - Rectus Abdominis
  { name: 'Crunch', muscle: 'ABS & CORE', subMuscle: 'Rectus Abdominis', secondaryMuscles: 'Obliques' },
  { name: 'Sit-Up', muscle: 'ABS & CORE', subMuscle: 'Rectus Abdominis', secondaryMuscles: 'Hip Flexors, Obliques' },
  { name: 'Hanging Leg Raise', muscle: 'ABS & CORE', subMuscle: 'Rectus Abdominis', secondaryMuscles: 'Hip Flexors, Forearms (Grip)' },
  { name: 'Cable Crunch', muscle: 'ABS & CORE', subMuscle: 'Rectus Abdominis', secondaryMuscles: 'Obliques, Hip Flexors' },
  { name: 'Weighted Decline Crunch', muscle: 'ABS & CORE', subMuscle: 'Rectus Abdominis', secondaryMuscles: 'Hip Flexors' },
  { name: 'Toes-to-Bar', muscle: 'ABS & CORE', subMuscle: 'Rectus Abdominis', secondaryMuscles: 'Lats, Forearms, Hip Flexors' },
  { name: 'Reverse Crunch', muscle: 'ABS & CORE', subMuscle: 'Rectus Abdominis', secondaryMuscles: 'Obliques' },
  { name: 'Jackknife Sit-Up', muscle: 'ABS & CORE', subMuscle: 'Rectus Abdominis', secondaryMuscles: 'Hip Flexors, Quads' },
  { name: 'Ab Wheel Rollout', muscle: 'ABS & CORE', subMuscle: 'Rectus Abdominis', secondaryMuscles: 'Lats, Serratus Anterior, Lower Back' },
  { name: 'Machine Crunch', muscle: 'ABS & CORE', subMuscle: 'Rectus Abdominis', secondaryMuscles: 'None' },
  { name: 'Stability Ball Crunch', muscle: 'ABS & CORE', subMuscle: 'Rectus Abdominis', secondaryMuscles: 'Core Stabilizers' },
  { name: 'V-Ups', muscle: 'ABS & CORE', subMuscle: 'Rectus Abdominis', secondaryMuscles: 'Hip Flexors, Quads' },
  { name: 'Knee Raises', muscle: 'ABS & CORE', subMuscle: 'Rectus Abdominis', secondaryMuscles: 'Hip Flexors' },
  { name: 'Frog Crunch', muscle: 'ABS & CORE', subMuscle: 'Rectus Abdominis', secondaryMuscles: 'Adductors, Obliques' },
  { name: 'Dead Bug', muscle: 'ABS & CORE', subMuscle: 'Rectus Abdominis', secondaryMuscles: 'Hip Flexors, Transverse Abdominis' },

  // ABS & CORE - Obliques
  { name: 'Russian Twist', muscle: 'ABS & CORE', subMuscle: 'Obliques', secondaryMuscles: 'Rectus Abdominis, Hip Flexors' },
  { name: 'Side Plank', muscle: 'ABS & CORE', subMuscle: 'Obliques', secondaryMuscles: 'Transverse Abdominis, Glute Medius' },
  { name: 'Cable Woodchopper', muscle: 'ABS & CORE', subMuscle: 'Obliques', secondaryMuscles: 'Shoulders, Core' },
  { name: 'Hanging Oblique Raise', muscle: 'ABS & CORE', subMuscle: 'Obliques', secondaryMuscles: 'Hip Flexors, Forearms' },
  { name: 'Decline Oblique Sit-Up', muscle: 'ABS & CORE', subMuscle: 'Obliques', secondaryMuscles: 'Hip Flexors' },
  { name: 'Bicycle Crunch', muscle: 'ABS & CORE', subMuscle: 'Obliques', secondaryMuscles: 'Rectus Abdominis, Hip Flexors' },
  { name: 'Oblique Crunch', muscle: 'ABS & CORE', subMuscle: 'Obliques', secondaryMuscles: 'Rectus Abdominis' },
  { name: 'Standing Side Bend', muscle: 'ABS & CORE', subMuscle: 'Obliques', secondaryMuscles: 'Core' },
  { name: 'Cable Side Bend', muscle: 'ABS & CORE', subMuscle: 'Obliques', secondaryMuscles: 'Core' },
  { name: 'Pallof Press', muscle: 'ABS & CORE', subMuscle: 'Obliques', secondaryMuscles: 'Shoulders, Glutes (Anti-rotation)' },
  { name: 'Landmine Twist', muscle: 'ABS & CORE', subMuscle: 'Obliques', secondaryMuscles: 'Shoulders, Core' },
  { name: 'Heel Touches', muscle: 'ABS & CORE', subMuscle: 'Obliques', secondaryMuscles: 'Rectus Abdominis' },
  { name: 'T-Rotation Push-Up', muscle: 'ABS & CORE', subMuscle: 'Obliques', secondaryMuscles: 'Chest, Triceps, Shoulders' },
  { name: 'Side V-Up', muscle: 'ABS & CORE', subMuscle: 'Obliques', secondaryMuscles: 'Hip Flexors' },
  { name: 'Seated Oblique Knee Tuck', muscle: 'ABS & CORE', subMuscle: 'Obliques', secondaryMuscles: 'Hip Flexors, Rectus Abdominis' },

  // ABS & CORE - Transverse Abdominis
  { name: 'Plank', muscle: 'ABS & CORE', subMuscle: 'Transverse Abdominis (Deep Core)', secondaryMuscles: 'Shoulders, Glutes, Quads' },
  { name: 'Hollow Hold', muscle: 'ABS & CORE', subMuscle: 'Transverse Abdominis (Deep Core)', secondaryMuscles: 'Quads, Hip Flexors' },
  { name: 'Stomach Vacuum', muscle: 'ABS & CORE', subMuscle: 'Transverse Abdominis (Deep Core)', secondaryMuscles: 'Pelvic Floor' },
  { name: 'Bird Dog', muscle: 'ABS & CORE', subMuscle: 'Transverse Abdominis (Deep Core)', secondaryMuscles: 'Glutes, Lower Back, Shoulders' },
  { name: 'Dead Bug (TA Focus)', muscle: 'ABS & CORE', subMuscle: 'Transverse Abdominis (Deep Core)', secondaryMuscles: 'Hip Flexors' },
  { name: 'Knee Tucks', muscle: 'ABS & CORE', subMuscle: 'Transverse Abdominis (Deep Core)', secondaryMuscles: 'Hip Flexors' },
  { name: 'Mountain Climbers', muscle: 'ABS & CORE', subMuscle: 'Transverse Abdominis (Deep Core)', secondaryMuscles: 'Shoulders, Triceps, Quads' },
  { name: 'Ball Stir-the-Pot', muscle: 'ABS & CORE', subMuscle: 'Transverse Abdominis (Deep Core)', secondaryMuscles: 'Shoulders, Lats' },
  { name: 'Isometric Hold', muscle: 'ABS & CORE', subMuscle: 'Transverse Abdominis (Deep Core)', secondaryMuscles: 'Full Body Tension' },
  { name: 'Bear Crawl', muscle: 'ABS & CORE', subMuscle: 'Transverse Abdominis (Deep Core)', secondaryMuscles: 'Shoulders, Quads, Core' },
  { name: 'Slow Controlled Leg Raises', muscle: 'ABS & CORE', subMuscle: 'Transverse Abdominis (Deep Core)', secondaryMuscles: 'Hip Flexors' },

  // ARMS - Biceps (Long Head)
  { name: 'Incline Dumbbell Curl', muscle: 'ARMS', subMuscle: 'Biceps (Long Head Focus)', secondaryMuscles: 'Brachialis, Forearms' },
  { name: 'Hammer Curl', muscle: 'ARMS', subMuscle: 'Biceps (Long Head Focus)', secondaryMuscles: 'Brachioradialis, Biceps' },
  { name: 'Cross-Body Hammer Curl', muscle: 'ARMS', subMuscle: 'Biceps (Long Head Focus)', secondaryMuscles: 'Brachioradialis, Brachialis' },
  { name: 'Dumbbell Alternating Curl', muscle: 'ARMS', subMuscle: 'Biceps (Long Head Focus)', secondaryMuscles: 'Forearms, Brachialis' },
  { name: 'Cable Rope Hammer Curl', muscle: 'ARMS', subMuscle: 'Biceps (Long Head Focus)', secondaryMuscles: 'Brachioradialis, Forearms' },
  { name: 'Reverse-Grip Curl', muscle: 'ARMS', subMuscle: 'Biceps (Long Head Focus)', secondaryMuscles: 'Brachioradialis, Forearms' },
  { name: 'Bayesian Cable Curl', muscle: 'ARMS', subMuscle: 'Biceps (Long Head Focus)', secondaryMuscles: 'Brachialis' },
  { name: 'Long-Head Focus Dumbbell Curl', muscle: 'ARMS', subMuscle: 'Biceps (Long Head Focus)', secondaryMuscles: 'Brachialis' },
  { name: 'Behind-the-Back Cable Curl', muscle: 'ARMS', subMuscle: 'Biceps (Long Head Focus)', secondaryMuscles: 'Brachialis' },
  { name: 'Drag Curl', muscle: 'ARMS', subMuscle: 'Biceps (Long Head Focus)', secondaryMuscles: 'Rear Delts' },
  { name: 'Dumbbell Supinating Curl', muscle: 'ARMS', subMuscle: 'Biceps (Long Head Focus)', secondaryMuscles: 'Forearms' },
  { name: 'Single-Arm Cable Curl', muscle: 'ARMS', subMuscle: 'Biceps (Long Head Focus)', secondaryMuscles: 'None' },
  { name: 'Cross-Chest Cable Curl', muscle: 'ARMS', subMuscle: 'Biceps (Long Head Focus)', secondaryMuscles: 'Brachialis' },
  { name: 'Concentration Hammer Curl', muscle: 'ARMS', subMuscle: 'Biceps (Long Head Focus)', secondaryMuscles: 'Brachioradialis' },
  { name: 'Machine Hammer Curl', muscle: 'ARMS', subMuscle: 'Biceps (Long Head Focus)', secondaryMuscles: 'Brachioradialis' },

  // ARMS - Biceps (Short Head)
  { name: 'Preacher Curl', muscle: 'ARMS', subMuscle: 'Biceps (Short Head Focus)', secondaryMuscles: 'Brachialis, Forearms' },
  { name: 'Spider Curl', muscle: 'ARMS', subMuscle: 'Biceps (Short Head Focus)', secondaryMuscles: 'Brachialis' },
  { name: 'Cable Preacher Curl', muscle: 'ARMS', subMuscle: 'Biceps (Short Head Focus)', secondaryMuscles: 'Forearms' },
  { name: 'Close-Grip Barbell Curl', muscle: 'ARMS', subMuscle: 'Biceps (Short Head Focus)', secondaryMuscles: 'Brachialis' },
  { name: 'Dumbbell Curl (Elbows Forward)', muscle: 'ARMS', subMuscle: 'Biceps (Short Head Focus)', secondaryMuscles: 'Brachialis' },
  { name: 'Machine Curl', muscle: 'ARMS', subMuscle: 'Biceps (Short Head Focus)', secondaryMuscles: 'None' },
  { name: 'High-Cable Curl', muscle: 'ARMS', subMuscle: 'Biceps (Short Head Focus)', secondaryMuscles: 'Front Delts (Slight)' },
  { name: 'EZ-Bar Curl', muscle: 'ARMS', subMuscle: 'Biceps (Short Head Focus)', secondaryMuscles: 'Brachialis, Forearms' },
  { name: 'Standing Cable Curl', muscle: 'ARMS', subMuscle: 'Biceps (Short Head Focus)', secondaryMuscles: 'Forearms' },
  { name: 'Double Dumbbell Curl', muscle: 'ARMS', subMuscle: 'Biceps (Short Head Focus)', secondaryMuscles: 'Core (Stabilization)' },
  { name: 'Zottman Curl', muscle: 'ARMS', subMuscle: 'Biceps (Short Head Focus)', secondaryMuscles: 'Brachioradialis, Forearm Extensors' },
  { name: 'Inner-Grip Curl', muscle: 'ARMS', subMuscle: 'Biceps (Short Head Focus)', secondaryMuscles: 'Brachialis' },
  { name: 'Seated Curl', muscle: 'ARMS', subMuscle: 'Biceps (Short Head Focus)', secondaryMuscles: 'None' },
  { name: 'Wrist-Supinated Curl', muscle: 'ARMS', subMuscle: 'Biceps (Short Head Focus)', secondaryMuscles: 'Forearms' },
  { name: 'Lying Cable Curl', muscle: 'ARMS', subMuscle: 'Biceps (Short Head Focus)', secondaryMuscles: 'None' },

  // ARMS - Triceps (Long Head)
  { name: 'Overhead Dumbbell Extension', muscle: 'ARMS', subMuscle: 'Triceps (Long Head Focus)', secondaryMuscles: 'Shoulders, Forearms' },
  { name: 'Cable Overhead Extension', muscle: 'ARMS', subMuscle: 'Triceps (Long Head Focus)', secondaryMuscles: 'Shoulders' },
  { name: 'Skull Crushers', muscle: 'ARMS', subMuscle: 'Triceps (Long Head Focus)', secondaryMuscles: 'Shoulders' },
  { name: 'Incline Skull Crushers', muscle: 'ARMS', subMuscle: 'Triceps (Long Head Focus)', secondaryMuscles: 'Shoulders (Increased Stretch)' },
  { name: 'Dumbbell Kickback', muscle: 'ARMS', subMuscle: 'Triceps (Long Head Focus)', secondaryMuscles: 'Rear Delts' },
  { name: 'Rope Overhead Extension', muscle: 'ARMS', subMuscle: 'Triceps (Long Head Focus)', secondaryMuscles: 'Shoulders, Forearms' },
  { name: 'Machine Overhead Extension', muscle: 'ARMS', subMuscle: 'Triceps (Long Head Focus)', secondaryMuscles: 'None' },
  { name: 'Landmine French Press', muscle: 'ARMS', subMuscle: 'Triceps (Long Head Focus)', secondaryMuscles: 'Shoulders, Core' },
  { name: 'Single-Arm Overhead Extension', muscle: 'ARMS', subMuscle: 'Triceps (Long Head Focus)', secondaryMuscles: 'Core' },
  { name: 'Barbell French Press', muscle: 'ARMS', subMuscle: 'Triceps (Long Head Focus)', secondaryMuscles: 'Shoulders' },

  // ARMS - Triceps (Lateral & Medial)
  { name: 'Tricep Pushdown (Rope)', muscle: 'ARMS', subMuscle: 'Triceps (Lateral & Medial Heads)', secondaryMuscles: 'Forearms' },
  { name: 'Tricep Pushdown (Bar)', muscle: 'ARMS', subMuscle: 'Triceps (Lateral & Medial Heads)', secondaryMuscles: 'Forearms' },
  { name: 'Reverse Grip Pushdown', muscle: 'ARMS', subMuscle: 'Triceps (Lateral & Medial Heads)', secondaryMuscles: 'Forearm Flexors' },
  { name: 'Cable Kickback (Triceps)', muscle: 'ARMS', subMuscle: 'Triceps (Lateral & Medial Heads)', secondaryMuscles: 'Rear Delts' },
  { name: 'Machine Tricep Extension', muscle: 'ARMS', subMuscle: 'Triceps (Lateral & Medial Heads)', secondaryMuscles: 'None' },
  { name: 'Close-Grip Bench Press', muscle: 'ARMS', subMuscle: 'Triceps (Lateral & Medial Heads)', secondaryMuscles: 'Chest, Front Delts' },
  { name: 'Diamond Push-Ups', muscle: 'ARMS', subMuscle: 'Triceps (Lateral & Medial Heads)', secondaryMuscles: 'Chest, Front Delts, Core' },
  { name: 'Smith Close-Grip Press', muscle: 'ARMS', subMuscle: 'Triceps (Lateral & Medial Heads)', secondaryMuscles: 'Chest' },
  { name: 'Dips', muscle: 'ARMS', subMuscle: 'Triceps (Lateral & Medial Heads)', secondaryMuscles: 'Chest, Front Delts' },
  { name: 'Weighted Dips', muscle: 'ARMS', subMuscle: 'Triceps (Lateral & Medial Heads)', secondaryMuscles: 'Chest, Front Delts' },
  { name: 'Underhand Rope Pushdown', muscle: 'ARMS', subMuscle: 'Triceps (Lateral & Medial Heads)', secondaryMuscles: 'Forearm Flexors' },
  { name: 'Cable Straight-Bar Extension', muscle: 'ARMS', subMuscle: 'Triceps (Lateral & Medial Heads)', secondaryMuscles: 'Forearms' },
  { name: 'Tricep Bench Dips', muscle: 'ARMS', subMuscle: 'Triceps (Lateral & Medial Heads)', secondaryMuscles: 'Chest, Front Delts' },
  { name: 'Dumbbell Neutral Kickback', muscle: 'ARMS', subMuscle: 'Triceps (Lateral & Medial Heads)', secondaryMuscles: 'Rear Delts' },
  { name: 'Reverse Grip Close Bench', muscle: 'ARMS', subMuscle: 'Triceps (Lateral & Medial Heads)', secondaryMuscles: 'Chest, Front Delts' },
  { name: 'Cable Wrist-Out Pushdown', muscle: 'ARMS', subMuscle: 'Triceps (Lateral & Medial Heads)', secondaryMuscles: 'Forearms' },
  { name: 'One-Arm Straight Bar Pushdown', muscle: 'ARMS', subMuscle: 'Triceps (Lateral & Medial Heads)', secondaryMuscles: 'None' },
  { name: 'Single-Dumbbell Neutral Extension', muscle: 'ARMS', subMuscle: 'Triceps (Lateral & Medial Heads)', secondaryMuscles: 'Shoulders' },
  { name: 'Tricep Hold', muscle: 'ARMS', subMuscle: 'Triceps (Lateral & Medial Heads)', secondaryMuscles: 'Forearms (Isometric)' },
  { name: 'Cable Cross-Body Extension', muscle: 'ARMS', subMuscle: 'Triceps (Lateral & Medial Heads)', secondaryMuscles: 'None' },

  // ARMS - FOREARMS
  { name: 'Wrist Curl', muscle: 'ARMS', subMuscle: 'Flexors & Extensors', secondaryMuscles: 'Fingers' },
  { name: 'Reverse Wrist Curl', muscle: 'ARMS', subMuscle: 'Flexors & Extensors', secondaryMuscles: 'Brachioradialis' },
  { name: 'Cable Wrist Flexion', muscle: 'ARMS', subMuscle: 'Flexors & Extensors', secondaryMuscles: 'Fingers' },
  { name: 'Dumbbell Wrist Twist', muscle: 'ARMS', subMuscle: 'Flexors & Extensors', secondaryMuscles: 'Full Forearm' },
  { name: 'Plate Pinch', muscle: 'ARMS', subMuscle: 'Flexors & Extensors', secondaryMuscles: 'Fingers, Thumb' },
  { name: 'Bar Hang', muscle: 'ARMS', subMuscle: 'Flexors & Extensors', secondaryMuscles: 'Lats, Shoulders, Core' },
  { name: 'Flexor Bar Roll', muscle: 'ARMS', subMuscle: 'Flexors & Extensors', secondaryMuscles: 'Fingers' },
  { name: 'Farmer Carry', muscle: 'ARMS', subMuscle: 'Flexors & Extensors', secondaryMuscles: 'Traps, Core, Glutes, Calves' },
  { name: 'Rope Hold', muscle: 'ARMS', subMuscle: 'Flexors & Extensors', secondaryMuscles: 'Fingers' },
  { name: 'Cable Finger Curl', muscle: 'ARMS', subMuscle: 'Flexors & Extensors', secondaryMuscles: 'None' },
  { name: 'Reverse Curl', muscle: 'ARMS', subMuscle: 'Flexors & Extensors', secondaryMuscles: 'Brachioradialis, Biceps' },
  { name: 'Wrist Extension', muscle: 'ARMS', subMuscle: 'Flexors & Extensors', secondaryMuscles: 'Brachioradialis' },
  { name: 'Cable Reverse Wrist Curl', muscle: 'ARMS', subMuscle: 'Flexors & Extensors', secondaryMuscles: 'Brachioradialis' },
  { name: 'Barbell Reverse Wrist Raise', muscle: 'ARMS', subMuscle: 'Flexors & Extensors', secondaryMuscles: 'Brachioradialis' },
  { name: 'Resistance Band Wrist Extension', muscle: 'ARMS', subMuscle: 'Flexors & Extensors', secondaryMuscles: 'Brachioradialis' },
  { name: 'Plate Wrist Extension', muscle: 'ARMS', subMuscle: 'Flexors & Extensors', secondaryMuscles: 'Brachioradialis' },
  { name: 'Dumbbell Reverse Twist', muscle: 'ARMS', subMuscle: 'Flexors & Extensors', secondaryMuscles: 'Full Forearm' },
  { name: 'Barbell Hold', muscle: 'ARMS', subMuscle: 'Flexors & Extensors', secondaryMuscles: 'Traps' },
  { name: 'Finger Extension Bands', muscle: 'ARMS', subMuscle: 'Flexors & Extensors', secondaryMuscles: 'Hand Health' },
  { name: 'Cable Knuckle-Up Extension', muscle: 'ARMS', subMuscle: 'Flexors & Extensors', secondaryMuscles: 'Brachioradialis' },
  { name: 'Hammer Curl (Forearm Focus)', muscle: 'ARMS', subMuscle: 'Flexors & Extensors', secondaryMuscles: 'Biceps, Brachialis' },
  { name: 'Fat Grip Curl', muscle: 'ARMS', subMuscle: 'Flexors & Extensors', secondaryMuscles: 'Biceps, Brachialis (Increased Grip Demand)' },

  // LEGS - Quads
  { name: 'Back Squat', muscle: 'LEGS', subMuscle: 'Quads', secondaryMuscles: 'Glutes, Hamstrings, Lower Back, Core' },
  { name: 'Front Squat', muscle: 'LEGS', subMuscle: 'Quads', secondaryMuscles: 'Upper Back, Core, Glutes' },
  { name: 'Leg Press', muscle: 'LEGS', subMuscle: 'Quads', secondaryMuscles: 'Glutes, Hamstrings' },
  { name: 'Hack Squat', muscle: 'LEGS', subMuscle: 'Quads', secondaryMuscles: 'Glutes' },
  { name: 'Bulgarian Split Squat', muscle: 'LEGS', subMuscle: 'Quads', secondaryMuscles: 'Glutes, Core' },
  { name: 'Walking Lunge', muscle: 'LEGS', subMuscle: 'Quads', secondaryMuscles: 'Glutes, Hamstrings, Calves' },
  { name: 'Step-Ups', muscle: 'LEGS', subMuscle: 'Quads', secondaryMuscles: 'Glutes, Calves' },
  { name: 'Sissy Squat', muscle: 'LEGS', subMuscle: 'Quads', secondaryMuscles: 'Core' },
  { name: 'Leg Extension', muscle: 'LEGS', subMuscle: 'Quads', secondaryMuscles: 'None' },
  { name: 'Goblet Squat', muscle: 'LEGS', subMuscle: 'Quads', secondaryMuscles: 'Core, Upper Back, Glutes' },
  { name: 'Zombie Squat', muscle: 'LEGS', subMuscle: 'Quads', secondaryMuscles: 'Upper Back, Core' },
  { name: 'Smith Machine Squat', muscle: 'LEGS', subMuscle: 'Quads', secondaryMuscles: 'Glutes' },
  { name: 'High-Bar Squat', muscle: 'LEGS', subMuscle: 'Quads', secondaryMuscles: 'Glutes, Lower Back' },
  { name: 'Pistol Squat', muscle: 'LEGS', subMuscle: 'Quads', secondaryMuscles: 'Core, Glutes, Calves (Balance)' },
  { name: 'Belt Squat', muscle: 'LEGS', subMuscle: 'Quads', secondaryMuscles: 'Glutes (No Spinal Loading)' },
  { name: 'Narrow Stance Leg Press', muscle: 'LEGS', subMuscle: 'Quads', secondaryMuscles: 'Outer Quads' },
  { name: 'Split Squat', muscle: 'LEGS', subMuscle: 'Quads', secondaryMuscles: 'Glutes' },
  { name: 'Landmine Squat', muscle: 'LEGS', subMuscle: 'Quads', secondaryMuscles: 'Core, Upper Back' },
  { name: 'Heel-Elevated Squat', muscle: 'LEGS', subMuscle: 'Quads', secondaryMuscles: 'None (Max Quad Isolation)' },
  { name: 'Sled Push', muscle: 'LEGS', subMuscle: 'Quads', secondaryMuscles: 'Glutes, Calves, Cardio' },

  // LEGS - Hamstrings & Glutes
  { name: 'Romanian Deadlift', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Glutes, Lower Back, Forearms' },
  { name: 'Lying Leg Curl', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Calves' },
  { name: 'Seated Leg Curl', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Calves' },
  { name: 'Nordic Curl', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Calves, Core' },
  { name: 'Glute-Ham Raise', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Glutes, Lower Back, Calves' },
  { name: 'Single-Leg RDL', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Core, Glutes, Calves (Balance)' },
  { name: 'Good Morning', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Lower Back, Glutes' },
  { name: 'Cable Leg Curl', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'None' },
  { name: 'Stability Ball Curl', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Glutes, Core' },
  { name: 'Machine Single-Leg Curl', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'None' },
  { name: 'Kettlebell RDL', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Glutes, Forearms' },
  { name: 'Dumbbell RDL', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Glutes, Forearms' },
  { name: 'Hip Hinge', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Glutes' },
  { name: 'Isometric Hamstring Hold', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Calves' },
  { name: 'Slider Leg Curl', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Glutes, Core' },
  { name: 'Reverse Hyperextension', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Glutes, Lower Back' },
  { name: 'Swiss Ball Curl Rollouts', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Glutes, Core' },
  { name: 'Kneeling Leg Curl', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'None' },
  { name: 'Band Leg Curl', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'None' },
  { name: 'Prone Ham Curl Machine', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Calves' },
  { name: 'Barbell Hip Thrust', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Hamstrings, Core' },
  { name: 'Glute Bridge', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Hamstrings' },
  { name: 'Cable Kickback (Glutes)', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Hamstrings' },
  { name: 'Machine Glute Kickback', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Hamstrings' },
  { name: 'Lunges (Long Step)', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Hamstrings, Quads' },
  { name: 'Frog Pumps', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Adductors' },
  { name: 'Banded Lateral Walk', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Glute Medius, Hips' },
  { name: 'Barbell Glute Bridge', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Hamstrings' },
  { name: 'Smith Machine Hip Thrust', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Hamstrings' },
  { name: 'Single-Leg Hip Thrust', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Core, Hamstrings' },
  { name: 'Hip Abduction Machine', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Glute Medius/Minimus' },
  { name: 'Cable Abduction', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Glute Medius, Core' },
  { name: 'Kettlebell Swing', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Hamstrings, Lower Back, Core, Shoulders' },
  { name: 'Curtsy Lunge', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Glute Medius, Quads' },
  { name: 'Low Cable Pull-Through', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Hamstrings, Lower Back' },
  { name: 'Reverse Lunge', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Quads, Hamstrings' },
  { name: 'Glute Hyperextension', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Hamstrings, Lower Back' },
  { name: 'Sumo Deadlift', muscle: 'LEGS', subMuscle: 'Hamstrings & Glutes', secondaryMuscles: 'Adductors, Glutes, Traps, Forearms' },

  // LEGS - Calves
  { name: 'Standing Calf Raise', muscle: 'LEGS', subMuscle: 'Calves', secondaryMuscles: 'Gastrocnemius' },
  { name: 'Seated Calf Raise', muscle: 'LEGS', subMuscle: 'Calves', secondaryMuscles: 'Soleus' },
  { name: 'Leg Press Calf Raise', muscle: 'LEGS', subMuscle: 'Calves', secondaryMuscles: 'Gastrocnemius' },
  { name: 'Donkey Calf Raise', muscle: 'LEGS', subMuscle: 'Calves', secondaryMuscles: 'Gastrocnemius' },
  { name: 'Smith Machine Calf Raise', muscle: 'LEGS', subMuscle: 'Calves', secondaryMuscles: 'Gastrocnemius' },
  { name: 'Single-Leg Calf Raise', muscle: 'LEGS', subMuscle: 'Calves', secondaryMuscles: 'Balance muscles' },
  { name: 'Toe Walk', muscle: 'LEGS', subMuscle: 'Calves', secondaryMuscles: 'None' },
  { name: 'Jump Rope', muscle: 'LEGS', subMuscle: 'Calves', secondaryMuscles: 'Cardio, Shoulders' },
  { name: 'Box Jumps', muscle: 'LEGS', subMuscle: 'Calves', secondaryMuscles: 'Quads, Glutes (Explosive)' },
  { name: 'Explosive Toe Press', muscle: 'LEGS', subMuscle: 'Calves', secondaryMuscles: 'Gastrocnemius' },
  { name: 'Tibialis Raise', muscle: 'LEGS', subMuscle: 'Calves', secondaryMuscles: 'Ankle Stability' },
  { name: 'Incline Calf Raise', muscle: 'LEGS', subMuscle: 'Calves', secondaryMuscles: 'Gastrocnemius' },
  { name: 'Barbell Calf Raise', muscle: 'LEGS', subMuscle: 'Calves', secondaryMuscles: 'Core, Gastrocnemius' },
  { name: 'Cable Calf Raise', muscle: 'LEGS', subMuscle: 'Calves', secondaryMuscles: 'Core' },
  { name: 'Hack Machine Calf Raise', muscle: 'LEGS', subMuscle: 'Calves', secondaryMuscles: 'Gastrocnemius' },

  // CARDIO
  { name: 'Running (Treadmill)', muscle: 'CARDIO', subMuscle: 'General Cardio', secondaryMuscles: 'Quads, Hamstrings, Calves' },
  { name: 'Cycling (Stationary)', muscle: 'CARDIO', subMuscle: 'General Cardio', secondaryMuscles: 'Quads, Glutes' },
  { name: 'Elliptical Trainer', muscle: 'CARDIO', subMuscle: 'General Cardio', secondaryMuscles: 'Full Body (Low Impact)' },
  { name: 'Rowing Machine', muscle: 'CARDIO', subMuscle: 'General Cardio', secondaryMuscles: 'Back, Legs, Arms, Core' },
  { name: 'Stair Climber', muscle: 'CARDIO', subMuscle: 'General Cardio', secondaryMuscles: 'Glutes, Quads, Calves' },
  { name: 'Burpees', muscle: 'CARDIO', subMuscle: 'General Cardio', secondaryMuscles: 'Chest, Shoulders, Quads, Core' },
  { name: 'Mountain Climbers (Cardio Focus)', muscle: 'CARDIO', subMuscle: 'General Cardio', secondaryMuscles: 'Shoulders, Core' },
  { name: 'Jumping Jacks', muscle: 'CARDIO', subMuscle: 'General Cardio', secondaryMuscles: 'Shoulders, Calves' },
  { name: 'Kettlebell Swings (Cardio Focus)', muscle: 'CARDIO', subMuscle: 'General Cardio', secondaryMuscles: 'Glutes, Hamstrings, Shoulders' },
  { name: 'Boxing (Shadow or Bag)', muscle: 'CARDIO', subMuscle: 'General Cardio', secondaryMuscles: 'Shoulders, Core, Back' },
];
